apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-scheduler-as-kube-scheduler
subjects:
- kind: ServiceAccount
  name: my-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: scheduler
    tier: control-plane
  name: my-scheduler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: scheduler
      tier: control-plane
  replicas: 1
  template:
    metadata:
      labels:
        component: scheduler
        tier: control-plane
        version: second
    spec:
      nodeName: master.workwork.shield-pg0.utah.cloudlab.us
      serviceAccountName: my-scheduler
      containers:
      - image: fuyuqi1995/base-scheduler
        name: kube-second-scheduler
        volumeMounts:
          - mountPath: "/data/"
            name: task-pv-storage
      volumes: 
          - name: task-pv-storage
            persistentVolumeClaim:
              claimName: pvc1-nfs-system
